# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 834)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_0_0 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_0_0.setObjectName("lineEdit_0_0")
        self.gridLayout_2.addWidget(self.lineEdit_0_0, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_0_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_0_1.setObjectName("lineEdit_0_1")
        self.gridLayout_2.addWidget(self.lineEdit_0_1, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.textEdit_0 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_0.setObjectName("textEdit_0")
        self.gridLayout_2.addWidget(self.textEdit_0, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_1_0 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_1_0.setObjectName("lineEdit_1_0")
        self.gridLayout_5.addWidget(self.lineEdit_1_0, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_1_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_1_1.setObjectName("lineEdit_1_1")
        self.gridLayout_5.addWidget(self.lineEdit_1_1, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.textEdit_1 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_1.setObjectName("textEdit_1")
        self.gridLayout_5.addWidget(self.textEdit_1, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_2_0 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2_0.setObjectName("lineEdit_2_0")
        self.gridLayout_6.addWidget(self.lineEdit_2_0, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_2_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2_1.setObjectName("lineEdit_2_1")
        self.gridLayout_6.addWidget(self.lineEdit_2_1, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_6.addWidget(self.textEdit_2, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_30 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color:green;font-size:20px;font-family:微软雅黑")
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.groupBox_11)
        self.label_101.setStyleSheet("color:green;font-size:20px;font-family:微软雅黑")
        self.label_101.setObjectName("label_101")
        self.gridLayout_7.addWidget(self.label_101, 0, 1, 1, 2)
        self.label_31 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color:red;font-size:20px;font-family:微软雅黑")
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.groupBox_11)
        self.label_102.setStyleSheet("color:red;font-size:20px;font-family:微软雅黑")
        self.label_102.setObjectName("label_102")
        self.gridLayout_7.addWidget(self.label_102, 1, 1, 1, 2)
        self.label_36 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color:green;font-size:20px;font-family:微软雅黑")
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 2, 0, 2, 2)
        self.label_103 = QtWidgets.QLabel(self.groupBox_11)
        self.label_103.setStyleSheet("color:green;font-size:20px;font-family:微软雅黑")
        self.label_103.setObjectName("label_103")
        self.gridLayout_7.addWidget(self.label_103, 3, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:green;font-size:20px;font-family:微软雅黑")
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 4, 0, 1, 2)
        self.label_104 = QtWidgets.QLabel(self.groupBox_11)
        self.label_104.setStyleSheet("color:#000;font-size:20px;font-family:微软雅黑")
        self.label_104.setObjectName("label_104")
        self.gridLayout_7.addWidget(self.label_104, 4, 2, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_11)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_7.addWidget(self.textBrowser, 5, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox_11, 0, 3, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_3_0 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3_0.setObjectName("lineEdit_3_0")
        self.gridLayout_3.addWidget(self.lineEdit_3_0, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEdit_3_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3_1.setObjectName("lineEdit_3_1")
        self.gridLayout_3.addWidget(self.lineEdit_3_1, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_3.addWidget(self.textEdit_3, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 0, 0, 1, 1)
        self.lineEdit_4_0 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_4_0.setObjectName("lineEdit_4_0")
        self.gridLayout_10.addWidget(self.lineEdit_4_0, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_4_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_4_1.setObjectName("lineEdit_4_1")
        self.gridLayout_10.addWidget(self.lineEdit_4_1, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 2, 0, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_10.addWidget(self.textEdit_4, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_5_0 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_5_0.setObjectName("lineEdit_5_0")
        self.gridLayout_9.addWidget(self.lineEdit_5_0, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_5_1 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_5_1.setObjectName("lineEdit_5_1")
        self.gridLayout_9.addWidget(self.lineEdit_5_1, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 2, 0, 1, 1)
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout_9.addWidget(self.textEdit_5, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 1, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.lineEdit_6_0 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_6_0.setObjectName("lineEdit_6_0")
        self.gridLayout_4.addWidget(self.lineEdit_6_0, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.lineEdit_6_1 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_6_1.setObjectName("lineEdit_6_1")
        self.gridLayout_4.addWidget(self.lineEdit_6_1, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 2, 0, 1, 1)
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit_6.setObjectName("textEdit_6")
        self.gridLayout_4.addWidget(self.textEdit_6, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 2, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 0, 0, 1, 1)
        self.lineEdit_7_0 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_7_0.setObjectName("lineEdit_7_0")
        self.gridLayout_11.addWidget(self.lineEdit_7_0, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 1, 0, 1, 1)
        self.lineEdit_7_1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_7_1.setObjectName("lineEdit_7_1")
        self.gridLayout_11.addWidget(self.lineEdit_7_1, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 2, 0, 1, 1)
        self.textEdit_7 = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit_7.setObjectName("textEdit_7")
        self.gridLayout_11.addWidget(self.textEdit_7, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_8, 2, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 0, 0, 1, 1)
        self.lineEdit_8_0 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_8_0.setObjectName("lineEdit_8_0")
        self.gridLayout_12.addWidget(self.lineEdit_8_0, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 1, 0, 1, 1)
        self.lineEdit_8_1 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_8_1.setObjectName("lineEdit_8_1")
        self.gridLayout_12.addWidget(self.lineEdit_8_1, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 2, 0, 1, 1)
        self.textEdit_8 = QtWidgets.QTextEdit(self.groupBox_9)
        self.textEdit_8.setObjectName("textEdit_8")
        self.gridLayout_12.addWidget(self.textEdit_8, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_9, 2, 2, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 0, 0, 1, 1)
        self.listView = QtWidgets.QListView(self.groupBox_10)
        self.listView.setObjectName("listView")
        self.gridLayout_8.addWidget(self.listView, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_10)
        self.label_28.setGeometry(QtCore.QRect(50, 130, 171, 16))
        self.label_28.setStyleSheet("color:green")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_10)
        self.label_29.setGeometry(QtCore.QRect(30, 110, 171, 16))
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.groupBox_10, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "手动线抄表 - ©联桥科技"))
        self.groupBox.setTitle(_translate("MainWindow", "一号检测窗口"))
        self.label.setText(_translate("MainWindow", "检测状态："))
        self.label_2.setText(_translate("MainWindow", "抄表结果："))
        self.label_3.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_2.setTitle(_translate("MainWindow", "二号检测窗口"))
        self.label_4.setText(_translate("MainWindow", "检测状态："))
        self.label_5.setText(_translate("MainWindow", "抄表结果："))
        self.label_6.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_3.setTitle(_translate("MainWindow", "三号检测窗口"))
        self.label_7.setText(_translate("MainWindow", "检测状态："))
        self.label_8.setText(_translate("MainWindow", "抄表结果："))
        self.label_9.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_11.setTitle(_translate("MainWindow", "抄表结果汇总"))
        self.label_30.setText(_translate("MainWindow", "通过："))
        self.label_101.setText(_translate("MainWindow", "9"))
        self.label_31.setText(_translate("MainWindow", "失败："))
        self.label_102.setText(_translate("MainWindow", "0"))
        self.label_36.setText(_translate("MainWindow", "测试数量："))
        self.label_103.setText(_translate("MainWindow", "9"))
        self.label_37.setText(_translate("MainWindow", "直通率："))
        self.label_104.setText(_translate("MainWindow", "100%"))
        self.groupBox_4.setTitle(_translate("MainWindow", "四号检测窗口"))
        self.label_10.setText(_translate("MainWindow", "检测状态："))
        self.label_11.setText(_translate("MainWindow", "抄表结果："))
        self.label_12.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_5.setTitle(_translate("MainWindow", "五号检测窗口"))
        self.label_13.setText(_translate("MainWindow", "检测状态："))
        self.label_14.setText(_translate("MainWindow", "抄表结果："))
        self.label_15.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_6.setTitle(_translate("MainWindow", "六号检测窗口"))
        self.label_16.setText(_translate("MainWindow", "检测状态："))
        self.label_17.setText(_translate("MainWindow", "抄表结果："))
        self.label_18.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_7.setTitle(_translate("MainWindow", "七号检测窗口"))
        self.label_19.setText(_translate("MainWindow", "检测状态："))
        self.label_20.setText(_translate("MainWindow", "抄表结果："))
        self.label_21.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_8.setTitle(_translate("MainWindow", "八号检测窗口"))
        self.label_22.setText(_translate("MainWindow", "检测状态："))
        self.label_23.setText(_translate("MainWindow", "抄表结果："))
        self.label_24.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_9.setTitle(_translate("MainWindow", "九号检测窗口"))
        self.label_25.setText(_translate("MainWindow", "检测状态："))
        self.label_26.setText(_translate("MainWindow", "抄表结果："))
        self.label_27.setText(_translate("MainWindow", "错误代码："))
        self.groupBox_10.setTitle(_translate("MainWindow", "控制区"))
        self.pushButton.setText(_translate("MainWindow", "开始抄表"))
        self.label_28.setText(_translate("MainWindow", "按钮可以用键盘ENTER代替"))
        self.label_29.setText(_translate("MainWindow", "Tips："))
